version: "3.3"

services:
  posters-site:
    build:
      context: site/
      dockerfile: Dockerfile
    command: yarn dev
    image: rodeoclash/posters-site:latest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "3000:3000"
    volumes:
      - ./site:/usr/src/app
