name: Continuous integration
on: [push]

jobs:
  linting:
    name: "Linting"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"

      - name: Check site linting
        run: npx prettier@2.0.2 --check ./site

  site-test:
    name: "Site tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"

      - name: Run site tests
        working-directory: ./site
        run: yarn install && yarn test
